TeamThreeCodes = { 
    "ANA": ["Anaheim Ducks", 24],
    "BOS" : ["Boston Bruins", 6],
    "BUF" : ["Buffalo Sabres", 7],
    "CGY" : ["Calgary Flames", 20],
    "CAR" : ["Carolina Hurricanes", 12],
    "CHI" : ["Chicago Blackhawks", 16],
    "COL" : ["Colorado Avalanche", 21],
    "CBJ" : ["Columbus Blue Jackets", 29],
    "DAL" : ["Dallas Stars", 25],
    "DET" : ["Detroit Red Wings", 17],
    "EDM" : ["Edmonton Oilers", 22],
    "FLA" : ["Florida Panthers", 13],
    "LAK" : ["Los Angeles Kings", 26],
    "MIN" : ["Minnesota Wilds", 30],
    "MTL" : ["Montreal Canadiens", 8],
    "NSH" : ["Nashville Predators", 18],
    "NJD" : ["New Jersey Devils", 1],
    "NYI" : ["New York Islanders", 2],
    "NYR" : ["New York Rangers", 3],
    "OTT" : ["Ottawa Senators", 9],
    "PHI" : ["Philadelphia Flyers", 4],
    "PIT" : ["Pittsburg Penguins", 5],
    "SJS" : ["San Jose Sharks", 28],
    "SEA" : ["Seattle Kraken", 55],
    "STL" : ["St. Louis Blues", 19],
    "TBL" : ["Tampa Bay Lightning", 14],
    "TOR" : ["Toronto Maple Leafs", 10],
    "UTA" : ["Utah Mammoth", 68],
    "VAN" : ["Vancouver Canucks", 23],
    "VGK" : ["Vegas Golden Knights", 54],
    "WSH" : ["Washington Capitals",15],
    "WPG" : ["Winnipeg Jets", 52],
}